---
title: "Vignette"
author: "Jessica Ayers"
date: "2023-06-22"
---

```{r, echo = FALSE}
knitr::opts_chunk$set(fig.path = "/Users/jessayers/Documents/ST 558/TOPIC 2/Project-1/")
```

# Packages Needed

```{r, message = FALSE}
library(httr)
library(dplyr)
library(jsonlite)
library(tidyverse)
library(GGally)
```

# Functions

Options for s include blue, red and green
Options for y include 2000, 2010 and 2020
There are 9 total combinations of possible modifications. 

```{r}
contactFunction <- function(s, y){

if((s == "blue") & (y == 2000)) {

blueData <- GET("http://www.omdbapi.com/?s=blue&y=2000&apikey=ca153ce0")
blueParsed <- fromJSON(rawToChar(blueData$content))

bluedf <- data.frame(blueParsed$Search$Title, blueParsed$Search$Year, blueParsed$Search$imdbID, blueParsed$Search$Type)
blue <- bluedf %>%
  as_tibble() %>%
  rename(Title = blueParsed.Search.Title, Year = blueParsed.Search.Year, imdbID = blueParsed.Search.imdbID, Type = blueParsed.Search.Type)

return(blue)
}

else if((s == "blue") & (y == 2010)){
  blueData <- GET("http://www.omdbapi.com/?s=blue&y=2010&apikey=ca153ce0")
  blueParsed <- fromJSON(rawToChar(blueData$content))

  bluedf <- data.frame(blueParsed$Search$Title, blueParsed$Search$Year, blueParsed$Search$imdbID, blueParsed$Search$Type)
  blue <- bluedf %>%
    as_tibble() %>%
    rename(Title = blueParsed.Search.Title, Year = blueParsed.Search.Year, imdbID = blueParsed.Search.imdbID, Type = blueParsed.Search.Type) 

return(blue)
}

else if((s == "blue") & (y == 2020)){
  blueData <- GET("http://www.omdbapi.com/?s=blue&y=2020&apikey=ca153ce0")
blueParsed <- fromJSON(rawToChar(blueData$content))

bluedf <- data.frame(blueParsed$Search$Title, blueParsed$Search$Year, blueParsed$Search$imdbID, blueParsed$Search$Type)
blue <- bluedf %>%
  as_tibble() %>%
  rename(Title = blueParsed.Search.Title, Year = blueParsed.Search.Year, imdbID = blueParsed.Search.imdbID, Type = blueParsed.Search.Type)

return(blue)
}

else if ((s == "red") & (y == 2000)){
  redData <- GET("http://www.omdbapi.com/?s=red&y=2000&apikey=ca153ce0")
redParsed <- fromJSON(rawToChar(redData$content))

reddf <- data.frame(redParsed$Search$Title, redParsed$Search$Year, redParsed$Search$imdbID, redParsed$Search$Type)
red <- reddf %>%
  as_tibble() %>%
  rename(Title = redParsed.Search.Title, Year = redParsed.Search.Year, imdbID = redParsed.Search.imdbID, Type = redParsed.Search.Type)

return(red)
}

else if ((s == "red") & (y == 2010)){
  redData <- GET("http://www.omdbapi.com/?s=red&y=2010&apikey=ca153ce0")
redParsed <- fromJSON(rawToChar(redData$content))

reddf <- data.frame(redParsed$Search$Title, redParsed$Search$Year, redParsed$Search$imdbID, redParsed$Search$Type)
red <- reddf %>%
  as_tibble() %>%
  rename(Title = redParsed.Search.Title, Year = redParsed.Search.Year, imdbID = redParsed.Search.imdbID, Type = redParsed.Search.Type) 

return(red)
}

else if((s == "red") & (y == 2020)){
  redData <- GET("http://www.omdbapi.com/?s=red&y=2020&apikey=ca153ce0")
redParsed <- fromJSON(rawToChar(redData$content))

reddf <- data.frame(redParsed$Search$Title, redParsed$Search$Year, redParsed$Search$imdbID, redParsed$Search$Type)
red <- reddf %>%
  as_tibble() %>%
  rename(Title = redParsed.Search.Title, Year = redParsed.Search.Year, imdbID = redParsed.Search.imdbID, Type = redParsed.Search.Type) 

return(red)
}

else if((s == "green") & (y == 2000)){
  greenData <- GET("http://www.omdbapi.com/?s=green&y=2000&apikey=ca153ce0")
greenParsed <- fromJSON(rawToChar(greenData$content))

greendf <- data.frame(greenParsed$Search$Title, greenParsed$Search$Year, greenParsed$Search$imdbID, greenParsed$Search$Type)
green <- greendf %>%
  as_tibble() %>%
  rename(Title = greenParsed.Search.Title, Year = greenParsed.Search.Year, imdbID = greenParsed.Search.imdbID, Type = greenParsed.Search.Type) 

return(green)
}

else if((s== "green") & (y == 2010)){
  greenData <- GET("http://www.omdbapi.com/?s=green&y=2010&apikey=ca153ce0")
greenParsed <- fromJSON(rawToChar(greenData$content))

greendf <- data.frame(greenParsed$Search$Title, greenParsed$Search$Year, greenParsed$Search$imdbID, greenParsed$Search$Type)
green <- greendf %>%
  as_tibble() %>%
  rename(Title = greenParsed.Search.Title, Year = greenParsed.Search.Year, imdbID = greenParsed.Search.imdbID, Type = greenParsed.Search.Type) 

return(green)
}

else if((s == "green") & (y == 2020)){
  greenData <- GET("http://www.omdbapi.com/?s=green&y=2020&apikey=ca153ce0")
greenParsed <- fromJSON(rawToChar(greenData$content))

greendf <- data.frame(greenParsed$Search$Title, greenParsed$Search$Year, greenParsed$Search$imdbID, greenParsed$Search$Type)
green <- greendf %>%
  as_tibble() %>%
  rename(Title = greenParsed.Search.Title, Year = greenParsed.Search.Year, imdbID = greenParsed.Search.imdbID, Type = greenParsed.Search.Type) 

return(green)
}

else(stop("invalid s or y argument"))

}
```


# Section 3

```{r, message = FALSE}
redData1 <- contactFunction(s = "red", y = 2000)
redData2 <- contactFunction(s = "red", y = 2010)
redData3 <- contactFunction(s = "red", y = 2020)
half <- full_join(redData1, redData2)
edaData <- full_join(half, redData3)
edaData
```

```{r}
#Create new variable
#initialize Sequel Variable
edaData$Sequel <- ""
for(i in 1:30){
  if(grepl("2", edaData$Title[i]) == "TRUE"){
    edaData$Sequel[i] = "Yes"
  }
  else {
    edaData$Sequel[i] = "No"
  }
}
edaData

#initialize length of title variable
edaData$lengthOfTitle <- 0
for(i in 1:30){
  edaData$lengthOfTitle[i] <- nchar(edaData$Title[i])
}
edaData
```

```{r}
#contingency tables
table(edaData$Year)
table(edaData$Type)
table(edaData$Type, edaData$Year)
table(edaData$Type, edaData$Year, edaData$Sequel)
```

```{r}
#numerical summaries for quantitative variables at each setting of the categorical variables
mean(edaData$lengthOfTitle)
median(edaData$lengthOfTitle)
sd(edaData$lengthOfTitle)
var(edaData$lengthOfTitle)
IQR(edaData$lengthOfTitle)

#each setting of year first
edaData %>% group_by(Year) %>%
summarise(avg = mean(lengthOfTitle), med = median(lengthOfTitle), var = var(lengthOfTitle))

#each setting of type
edaData %>% group_by(Type) %>%
summarise(avg = mean(lengthOfTitle), med = median(lengthOfTitle), var = var(lengthOfTitle))

#each setting of Sequel
edaData %>% group_by(Sequel) %>%
summarise(avg = mean(lengthOfTitle), med = median(lengthOfTitle), var = var(lengthOfTitle))
```

```{r}
#bar plot
g <- ggplot(data = edaData, aes(x = Year))
g + geom_bar(aes(fill = Type)) + 
  labs(title = "Bar Plot of Years of Movies, Series, and Games") +
  coord_flip()
```

```{r}
#histogram
g <- ggplot(edaData, aes(x = lengthOfTitle))
g + geom_histogram(color = "black", fill = "white",
size = 2, binwidth = 3) + 
  labs(title = "Histogram of Length of Title", x = "Length of Title", y = "Count")
```

```{r}
#Boxplot
g <- ggplot(edaData, aes(x = Type, y = lengthOfTitle))
g + geom_boxplot(fill = "red")
```
```{r}
g <- ggplot(edaData, aes(x = Year, y = lengthOfTitle))
g + geom_boxplot(fill = "red") + 
stat_summary(fun.y = median, geom = "line",
lwd = 1.5, aes(group = Type, col = Type))
```

```{r}
#scatterplot
g <- ggplot(edaData, aes(x = lengthOfTitle, y = imdbID))
g + geom_point() +
  facet_grid(~edaData$Type) + 
  geom_text(aes(label = Year))
```

```{r}
g <- ggplot(edaData, aes(x = Sequel, y = lengthOfTitle, color = Year))
g + geom_line(lwd = 4)
```


